Write-Host -ForegroundColor Yellow "Creating SQL dump..."

$null > INSTALL.sql
Remove-Item build/extensions/available/openvk/install/sqls/00012-support-better-greetings.sql
Get-Content -Path build/install/init-db.sql | Add-Content -Path INSTALL.sql
Get-Content -Path build/extensions/available/openvk/install/init-event-db.sql | Add-Content -Path INSTALL.sql
Get-Content -Path build/extensions/available/openvk/install/init-static-db.sql | Add-Content -Path INSTALL.sql
Get-Content -Path build/extensions/available/openvk/install/sqls/*.sql | Add-Content -Path INSTALL.sql
Move-Item INSTALL.sql -Destination build/INSTALL.sql -Force

Write-Host -ForegroundColor Yellow "Writing instructions..."

Copy-Item src/install.txt -Destination build/autogenerated-install-readme.txt -Force
Remove-Item build/INSTALL.md -Force
